const photos=[['Welcome to CS.','Our name on the outside. Our commitment to making on the inside.','CS Ply and Boards factory exterior'],['Where layers come together.','A closer look at the plywood sheets and press on our production floor.','Plywood sheets and press'],['Inside the production floor.','Explore the equipment and working spaces behind our materials.','Boiler and machinery inside the factory'],['A different perspective.','An open view of our machinery and covered manufacturing space.','Manufacturing machinery in a covered factory'],['The making, up close.','Step inside the facility and take a closer look at our production equipment.','Factory press and production machinery'],['Space for the process.','A view across the floor of the CS Ply & Boards facility.','Interior manufacturing floor'],['Behind the scenes.','Another detail from the equipment at our manufacturing facility.','Board production equipment']];
let current=0;const main=document.querySelector('#gallery-image'),thumbs=document.querySelector('.thumbnails'),dialog=document.querySelector('#lightbox');
photos.forEach((p,i)=>{const b=document.createElement('button');b.setAttribute('aria-label','Show photo '+(i+1)+': '+p[2]);const img=document.createElement('img');img.src='assets/factory-'+i+'.jpg';img.alt='';img.loading='lazy';b.append(img);b.addEventListener('click',()=>select(i));thumbs.append(b)});
function select(i){current=(i+photos.length)%photos.length;main.src='assets/factory-'+current+'.jpg';main.alt=photos[current][2];document.querySelector('#gallery-number').innerHTML=String(current+1).padStart(2,'0')+' <small>/ 07</small>';document.querySelector('#gallery-title').textContent=photos[current][0];document.querySelector('#gallery-description').textContent=photos[current][1];[...thumbs.children].forEach((b,j)=>{b.classList.toggle('active',j===current);b.setAttribute('aria-pressed',j===current?'true':'false')});if(dialog.open)updateDialog()}
function updateDialog(){dialog.querySelector('img').src=main.src;dialog.querySelector('img').alt=main.alt;dialog.querySelector('p').textContent=photos[current][0]}
document.querySelector('#prev').onclick=()=>select(current-1);document.querySelector('#next').onclick=()=>select(current+1);document.querySelector('#open-photo').onclick=()=>{updateDialog();dialog.showModal()};dialog.querySelector('.close').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});dialog.addEventListener('keydown',e=>{if(e.key==='ArrowRight')select(current+1);if(e.key==='ArrowLeft')select(current-1)});document.querySelector('#year').textContent=new Date().getFullYear();select(0);
const art=document.querySelector('#hero-art');if(matchMedia('(hover: hover) and (prefers-reduced-motion: no-preference)').matches){art.addEventListener('pointermove',e=>{const r=art.getBoundingClientRect();art.style.setProperty('--ry',((e.clientX-r.left)/r.width-.5)*9+'deg');art.style.setProperty('--rx',-((e.clientY-r.top)/r.height-.5)*7+'deg')});art.addEventListener('pointerleave',()=>{art.style.setProperty('--ry','0deg');art.style.setProperty('--rx','0deg')})}
// A silent photo film: one clock drives the scene, crossfade, and progress.
(()=>{
const film=document.querySelector('#film'),frames=[...film.querySelectorAll('.cinema-frame')],chapters=film.querySelector('.film-chapters'),toggle=film.querySelector('#film-toggle');
const captions=['Where it all begins.','Strength, layer by layer.','The energy behind the making.','A closer look at our world.','From process to possibility.','Space for what comes next.','CS Ply & Boards.'];
const reduced=matchMedia('(prefers-reduced-motion: reduce)');let playing=!reduced.matches,inView=false,ready=false,index=0,front=0,elapsed=0,fade=1200,last=0,raf=0;const duration=6500,crossfade=1200;
const bars=captions.map((caption,i)=>{const b=document.createElement('button');b.type='button';b.setAttribute('aria-label','Scene '+(i+1)+': '+caption);const bar=document.createElement('span');b.append(bar);const preview=document.createElement('span');preview.className='scene-preview';preview.setAttribute('aria-hidden','true');const image=document.createElement('img');image.src='assets/factory-'+i+'.jpg';image.alt='';const title=document.createElement('small');title.textContent=String(i+1).padStart(2,'0')+' / '+caption;preview.append(image,title);b.append(preview);b.onclick=()=>{playing=false;show(i);fade=crossfade;render();sync()};chapters.append(b);return bar});
function label(){if(!reduced.matches){film.querySelector('.cinema-copy').animate([{opacity:0,transform:'translateY(18px)'},{opacity:1,transform:'translateY(0)'}],{duration:1000,easing:'ease-out'})}film.querySelector('#film-caption').textContent=captions[index];film.querySelector('#film-count').textContent=String(index+1).padStart(2,'0')+' / 07';bars.forEach((b,i)=>b.parentElement.setAttribute('aria-pressed',String(i===index)))}
function show(i){index=i;front=1-front;elapsed=0;fade=reduced.matches?crossfade:0;frames[front].src='assets/factory-'+index+'.jpg';frames[front].style.zIndex='1';frames[1-front].style.zIndex='0';label()}
function render(){if(!reduced.matches&&matchMedia('(pointer: coarse)').matches){film.style.setProperty('--orbit-x',Math.sin(elapsed/duration*Math.PI*2)*.65+'deg');film.style.setProperty('--orbit-y',Math.cos(elapsed/duration*Math.PI*2)*.9+'deg')}frames[front].style.opacity=String(Math.min(1,fade/crossfade));frames[1-front].style.opacity='1';frames[front].style.transform=reduced.matches?'none':'scale('+(1.025+elapsed/duration*.075)+') translateY('+(-elapsed/duration*1.5)+'%)';bars.forEach((b,i)=>b.style.transform='scaleX('+(i<index?1:i===index?elapsed/duration:0)+')')}
function tick(now){raf=0;const delta=last?Math.min(now-last,100):0;last=now;elapsed+=delta;fade+=delta;if(elapsed>=duration)show((index+1)%captions.length);render();raf=requestAnimationFrame(tick)}
function sync(){film.classList.toggle('motion-paused',!playing||reduced.matches);toggle.textContent=playing?'Ⅱ Pause':'▶ Play';toggle.setAttribute('aria-label',(playing?'Pause':'Play')+' factory photo film');if(raf)cancelAnimationFrame(raf);raf=0;last=0;if(playing&&ready&&inView&&!document.hidden)raf=requestAnimationFrame(tick)}
function manualStep(offset){playing=false;show((index+offset+captions.length)%captions.length);fade=crossfade;render();sync()}
film.querySelector('#scene-prev').onclick=()=>manualStep(-1);film.querySelector('#scene-next').onclick=()=>manualStep(1);
film.addEventListener('keydown',e=>{if(e.key==='ArrowRight'){e.preventDefault();manualStep(1)}if(e.key==='ArrowLeft'){e.preventDefault();manualStep(-1)}});
let touchStart=null;film.addEventListener('touchstart',e=>{if(!e.target.closest('button,a'))touchStart=[e.touches[0].clientX,e.touches[0].clientY]},{passive:true});film.addEventListener('touchend',e=>{if(!touchStart)return;const dx=e.changedTouches[0].clientX-touchStart[0],dy=e.changedTouches[0].clientY-touchStart[1];if(Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy)*1.5)manualStep(dx<0?1:-1);touchStart=null},{passive:true});film.addEventListener('touchcancel',()=>{touchStart=null},{passive:true});
const expand=film.querySelector('#tour-expand'),tour=document.querySelector('#tour-dialog'),anchor=document.createComment('factory-tour-position');film.before(anchor);let previousOverflow='';
expand.onclick=()=>{if(tour.open){tour.close();return}previousOverflow=document.body.style.overflow;tour.append(film);tour.showModal();document.body.style.overflow='hidden';expand.textContent='× Exit immersive view';inView=true;sync();expand.focus()};
tour.addEventListener('close',()=>{anchor.after(film);document.body.style.overflow=previousOverflow;expand.textContent='⛶ Enter immersive view';expand.focus();sync()});
film.querySelector('.film-discover').addEventListener('click',()=>{if(tour.open)tour.close()});
film.addEventListener('pointermove',e=>{if(reduced.matches||!playing||e.pointerType!=='mouse')return;const r=film.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;film.style.setProperty('--drift-x',x*-30+'px');film.style.setProperty('--drift-y',y*-22+'px');film.style.setProperty('--copy-x',x*10+'px');film.style.setProperty('--copy-y',y*7+'px');film.style.setProperty('--light-x',(x+.5)*100+'%');film.style.setProperty('--light-y',(y+.5)*100+'%');film.classList.add('mouse-inside')});film.addEventListener('pointerleave',()=>{film.style.setProperty('--drift-x','0px');film.style.setProperty('--drift-y','0px');film.style.setProperty('--copy-x','0px');film.style.setProperty('--copy-y','0px');film.classList.remove('mouse-inside')});
toggle.onclick=()=>{playing=!playing;sync()};new IntersectionObserver(entries=>{inView=entries[0].isIntersecting;sync()},{threshold:.15}).observe(film);document.addEventListener('visibilitychange',sync);reduced.addEventListener('change',()=>{if(reduced.matches)playing=false;render();sync()});
Promise.all(captions.map((_,i)=>new Promise(resolve=>{const img=new Image();img.onload=resolve;img.onerror=resolve;img.src='assets/factory-'+i+'.jpg'}))).then(()=>{ready=true;sync()});label();render();sync();
})();

// Pointer-only depth: links keep their native mouse, keyboard, and touch behavior.
(()=>{
 const enabled=matchMedia('(hover: hover) and (pointer: fine) and (prefers-reduced-motion: no-preference)');
 const cards=[...document.querySelectorAll('.material-card')];
 function reset(card){['--tilt-x','--tilt-y','--shine-x','--shine-y'].forEach(p=>card.style.removeProperty(p));card.classList.remove('pointer-tilt')}
 cards.forEach(card=>{card.addEventListener('pointermove',e=>{if(!enabled.matches||e.pointerType!=='mouse')return;const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;card.style.setProperty('--tilt-x',(y-.5)*-7+'deg');card.style.setProperty('--tilt-y',(x-.5)*9+'deg');card.style.setProperty('--shine-x',x*100+'%');card.style.setProperty('--shine-y',y*100+'%');card.classList.add('pointer-tilt')});card.addEventListener('pointerleave',()=>reset(card));card.addEventListener('pointercancel',()=>reset(card))});
 enabled.addEventListener('change',()=>{if(!enabled.matches)cards.forEach(reset)});
})();

// Mobile depth follows native scrolling. No gesture interception or sensor access.
(()=>{
 const mobile=matchMedia('(pointer: coarse) and (prefers-reduced-motion: no-preference)');
 const film=document.querySelector('#film'),hero=document.querySelector('.hero-art');
 const cards=[...document.querySelectorAll('.material-card')],targets=[film,hero,...cards],visible=new Set();
 let pending=0;
 const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
 function draw(){pending=0;if(!mobile.matches||document.hidden)return;const height=innerHeight;
  visible.forEach(el=>{const r=el.getBoundingClientRect(),progress=clamp((height/2-r.top-r.height/2)/(height/2+r.height/2),-1,1);
   if(el===film){if(!film.classList.contains('motion-paused')){film.style.setProperty('--mobile-pan',progress*23+'px');film.style.setProperty('--mobile-copy',progress*-10+'px');film.style.setProperty('--mobile-lean',progress*2+'deg')}}
   else if(el===hero){el.style.setProperty('--mobile-photo-tilt',progress*9+'deg');el.style.setProperty('--mobile-photo-lift',progress*-22+'px');el.style.setProperty('--mobile-float-lift',progress*24+'px')}
   else{el.style.setProperty('--mobile-card-tilt',progress*-7+'deg');el.style.setProperty('--mobile-card-pan',progress*17+'px')}
  });
 }
 function schedule(){if(!pending&&mobile.matches&&!document.hidden)pending=requestAnimationFrame(draw)}
 new IntersectionObserver(entries=>{entries.forEach(e=>e.isIntersecting?visible.add(e.target):visible.delete(e.target));schedule()},{rootMargin:'80px'}).observe(film);
 const observer=new IntersectionObserver(entries=>{entries.forEach(e=>e.isIntersecting?visible.add(e.target):visible.delete(e.target));schedule()},{rootMargin:'80px'});[hero,...cards].forEach(el=>observer.observe(el));
 window.addEventListener('scroll',schedule,{passive:true});window.addEventListener('resize',schedule,{passive:true});document.querySelector('#tour-dialog').addEventListener('scroll',schedule,{passive:true});document.addEventListener('visibilitychange',schedule);
 targets.forEach(el=>{
  el.addEventListener('pointermove',e=>{if(!mobile.matches||e.pointerType!=='touch'||e.target.closest('button,a'))return;if(el===film&&film.classList.contains('motion-paused'))return;const r=el.getBoundingClientRect(),x=clamp((e.clientX-r.left)/r.width-.5,-.5,.5),y=clamp((e.clientY-r.top)/r.height-.5,-.5,.5);el.style.setProperty('--touch-y',x*5+'deg');el.style.setProperty('--touch-x',y*-4+'deg')},{passive:true});
  function reset(){el.style.setProperty('--touch-x','0deg');el.style.setProperty('--touch-y','0deg')}
  el.addEventListener('pointerup',reset,{passive:true});el.addEventListener('pointercancel',reset,{passive:true});
 });
 mobile.addEventListener('change',()=>{if(!mobile.matches){if(pending)cancelAnimationFrame(pending);pending=0;targets.forEach(el=>['--touch-x','--touch-y','--mobile-pan','--mobile-copy','--mobile-lean','--mobile-photo-tilt','--mobile-photo-lift','--mobile-float-lift','--mobile-card-tilt','--mobile-card-pan'].forEach(v=>el.style.removeProperty(v)))}else schedule()});schedule();
})();
